"""Probe an OpenAI-compatible chat endpoint for the capabilities this agent needs.

Reads the endpoint and credential from the environment, never from a file:

    TR_BASE   e.g. https://tokenrhythm.studio/v1
    TR_KEY    the API key

Nothing here writes the key anywhere. Results go to a UTF-8 JSON file so the
console can stay ASCII (the Windows console codepage mangles Chinese otherwise).

What it answers, in order of how much the design depends on it:
  1. Which models exist.
  2. Does a plain chat completion work.
  3. Does `response_format: {"type": "json_object"}` work.
  4. Does `response_format: {"type": "json_schema", ...}` work, and does it accept a
     schema generated by pydantic `model_json_schema()`?

(4) matters most: if the endpoint can enforce our own schema, the intake stage
cannot return a field with the wrong type, which is the single most common failure
this project has had to defend against.
"""
from __future__ import annotations

import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

# Running this file directly puts scripts/ on sys.path, not the project root, so the
# pydantic schema probe would fail to import reactor_agent. Add the root explicitly.
ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

BASE = os.environ.get('TR_BASE', '')
KEY = os.environ.get('TR_KEY', '')
OUT = ROOT / '_demo' / 'llm-probe.json'


def call(path: str, payload: dict | None = None, method: str | None = None,
         timeout: int = 120):
    """POST when a payload is supplied, GET otherwise.

    The method must not default to GET independently of the payload: doing that
    made this probe report 404 for /chat/completions while an identical manual call
    succeeded, because the request went out as a GET.
    """
    if not BASE or not KEY:
        return None, 'TR_BASE and TR_KEY must be set in the environment'
    if method is None:
        method = 'POST' if payload is not None else 'GET'
    url = BASE.rstrip('/') + path
    data = json.dumps(payload).encode('utf-8') if payload is not None else None
    request = urllib.request.Request(url, data=data, method=method)
    request.add_header('Authorization', 'Bearer ' + KEY)
    if data:
        request.add_header('Content-Type', 'application/json')
    started = time.time()
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return response.status, json.loads(response.read().decode('utf-8'))
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode('utf-8', 'replace')[:600]
        return exc.code, {'error': detail}
    except Exception as exc:                       # noqa: BLE001 - report everything
        return None, {'error': '%s: %s' % (type(exc).__name__, exc)}


def elapsed(started: float) -> float:
    return round(time.time() - started, 2)


def main() -> int:
    report: dict = {'base': BASE, 'key_present': bool(KEY), 'probes': {}}

    # ---------------------------------------------------------------- models
    status, body = call('/models')
    ids = [m.get('id') for m in body.get('data', [])] if isinstance(body, dict) else []
    report['probes']['models'] = {'http': status, 'count': len(ids), 'ids': ids}

    models = [m for m in ids if m]
    # TR_MODEL wins; otherwise take the first preferred name that exists.
    preferred = os.environ.get('TR_MODEL') or next(
        (m for m in ('deepseek-v4-pro-0813', 'deepseek-v4-flash-0731',
                     'deepseek-flash', 'glm-5.3-flash') if m in models), None)
    model = preferred or (models[0] if models else '')
    report['probe_model'] = model
    if model not in models:
        report['model_warning'] = ('%r is not in the /models list; the request may '
                                   'still work if the service accepts it' % model)

    prompt = ('甲苯歧化反应：2C7H8 -> C6H6 + C8H10。进料甲苯 10000 kg/h，'
              '进料温度 380 摄氏度，操作压力 2.5 MPa，甲苯转化率 50%。'
              '请提取结构化需求。')

    # ------------------------------------------------------- plain completion
    started = time.time()
    status, body = call('/chat/completions', {
        'model': model, 'max_tokens': 300,
        'messages': [{'role': 'user', 'content': prompt}]})
    text = ''
    if status == 200 and body.get('choices'):
        text = body['choices'][0].get('message', {}).get('content', '')
    report['probes']['plain_chat'] = {
        'http': status, 'seconds': elapsed(started),
        'reply_head': text[:300], 'usage': body.get('usage') if status == 200 else None,
        'error': body.get('error') if status != 200 else None}

    # ------------------------------------------------------------ json_object
    started = time.time()
    status, body = call('/chat/completions', {
        'model': model, 'max_tokens': 500,
        'response_format': {'type': 'json_object'},
        'messages': [
            {'role': 'system', 'content': 'Reply with JSON only.'},
            {'role': 'user', 'content': prompt + ' 以 JSON 输出，字段：'
                                                'components(数组)、'
                                                'conversion_percent(数字)、'
                                                'feed_mass_kg_per_h(数字)。'}]})
    parsed_ok = False
    parsed = None
    if status == 200 and body.get('choices'):
        raw = body['choices'][0].get('message', {}).get('content', '')
        try:
            parsed = json.loads(raw)
            parsed_ok = True
        except Exception:
            parsed = raw[:300]
    report['probes']['json_object'] = {
        'http': status, 'seconds': elapsed(started), 'parsed': parsed_ok,
        'result': parsed, 'error': body.get('error') if status != 200 else None}

    # ------------------------------------------- json_schema from our pydantic
    try:
        from reactor_agent.schemas import ProcessRequest
        schema = ProcessRequest.model_json_schema()
        schema_ok = True
    except Exception as exc:                       # noqa: BLE001
        schema, schema_ok = {'error': str(exc)}, False
    report['probes']['pydantic_schema_available'] = schema_ok

    started = time.time()
    status, body = call('/chat/completions', {
        'model': model, 'max_tokens': 900,
        'response_format': {'type': 'json_schema',
                            'json_schema': {'name': 'ProcessRequest',
                                            'strict': True,
                                            'schema': schema}},
        'messages': [
            {'role': 'system', 'content': 'Extract the request into the given schema. '
                                          'Use only fields defined there.'},
            {'role': 'user', 'content': prompt}]})
    schema_parsed = None
    if status == 200 and body.get('choices'):
        raw = body['choices'][0].get('message', {}).get('content', '')
        try:
            schema_parsed = json.loads(raw)
        except Exception:
            schema_parsed = raw[:300]
    report['probes']['json_schema'] = {
        'http': status, 'seconds': elapsed(started), 'result': schema_parsed,
        'error': body.get('error') if status != 200 else None}

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding='utf-8')

    # ASCII summary for the console.
    print('probe model      : %s' % model)
    print('models           : %d' % len(ids))
    for name in ('plain_chat', 'json_object', 'json_schema'):
        probe = report['probes'][name]
        print('%-17s: http=%s %.2fs %s' % (
            name, probe['http'], probe['seconds'],
            '' if not probe.get('error') else 'ERROR'))
    print('pydantic schema  : %s' % ('available' if schema_ok else 'FAILED'))
    print('full report      : %s' % OUT)
    return 0


if __name__ == '__main__':
    sys.exit(main())
